package frc.robot.Autonomous;

public enum AutoCmds {
    FOLLOW_WITH_POSE_AIM,

    FOLLOW_WITH_SHOOT_SPKLL_AIM,
    FOLLOW_WITH_SHOOT_SPKPOD_AIM,
    FOLLOW_WITH_SHOOT_SPKLIN_AIM,
    FOLLOW_WITH_SHOOT_SPKSUB_AIM,

    FOLLOW_WITH_FULL_SPKLL_AIM,
    FOLLOW_WITH_FULL_SPKPOD_AIM,
    FOLLOW_WITH_FULL_SPKLIN_AIM,
    FOLLOW_WITH_FULL_SPKSUB_AIM,

    FOLLOW_WITH_PASSTHROUGH,

    FOLLOW,
    SCORE,
    POSE_AIM,

    FULL_SPKLL_AIM,
    FULL_SPKPOD_AIM,
    FULL_SPKLIN_AIM,
    FULL_SPKSUB_AIM,

    SHOOT_SPKLL_AIM,
    SHOOT_SPKPOD_AIM,
    SHOOT_SPKLIN_AIM,
    SHOOT_SPKSUB_AIM
}